- tests/infra/server.py
- tests/test_http.py
- Ensure port is available
- Provide host name via context manager
> Update test http server

- streaming_urls/http.py
- tests/test_http.py
This is useful for verifying data integerity during download.
> Add method to parse checksum headers.

- streaming_urls/reader.py
This more closely associates functionality to the point of usage.
> Use static method for fetch part

- tests/test_reader.py
- tests/test_streaming_urls.py
This tests functionality more directly.
> Refactor tests

- streaming_urls/reader.py
- tests/test_reader.py
Reads data into shared memory using a single connection. The connection is kept alive over the course of the read/download operation.
Schematically, this works as follows:
- A shared memory buffer is created, and referenced with circular coordinates.
- Available data in the buffer is referenced with rear and forward cursers. The size of available data is `forward_curser - rear_curser`
- A producer process reads data into the buffer, advancing the forward curser. As space becomes available in the buffer (i.e., the rear curser advances), additional data is read.
- A consumer process passes referenced buffer regions to the user, advancing the rear curser after data is consumed by the caller.
- Buffer locations are communicated with inter-process pipes.
> Add single connection keep-alive reads

- scripts/download.py
- streaming_urls/__init__.py
- streaming_urls/reader.py
- tests/test_streaming_urls.py
The separates logic for downloader and user feedback.
> Refactor downloader

- getm/checksum.py
- tests/test_checksum.py
> Introduce MD5 getm checksum

- getm/progress.py
> Human readable sizes in progress indicators

- getm/cli.py
- tests/test_cli.py
> Introduce batched downloads

- getm/checksum.py
Also add convenience class to verity caller supplied checksums.
> Add checksum algo enumeration, No-op checksum

- getm/cli.py
- getm/utils.py
- tests/test_utils.py
This prevents hard link failure during download finalize.
closes #76
> Temp location uses same disk as target

- getm/concurrent/buffers.py
- getm/reader.py
This removes the possibility of Pipe deadlocks
> Use shared memory for interprocess communication

- getm/cli.py
Towards adding support for verbosity levels.
> Make logger available to CLI code

- getm/cli.py
`-v` for more verbose, `-vv` for much more verbose.
> Add verbosity modes to CLI

- getm/cli.py
> Ensure multipart buffer is only sized once

- tests/infra/__init__.py
This is useful for sane test output.
> Util function to quiet stdout, stderr, and logging

- getm/cli.py
This will be useful in the future to coherantly exit the program
based on diverse conditions.
> Refactor CLI logging with stateful structure

- getm/cli.py
- tests/test_cli.py
Default to exit on the first errored download.
Add argument to keep on keeping on instead.
closes #101
> CLI defaults to fails fast, argument to fail slow

- getm/cli.py
If the URL is inaccessable report content of response, and error.
> Check for URL accessibility before download

- getm/cli.py
This makes two things simpler:
- Error reporting without adding state
- Changing queuing schemes
> Add _download utility method

- getm/cli.py
- tests/test_cli.py
The idea is to get small downloads out of the way quickly.
> Use ConcurrentHeap to prioritize small downloads

- getm/utils.py
- tests/test_utils.py
> Create subdirectores as needed for download target

- getm/progress.py
- tests/test_progress.py
The progress bar is updates more frequently, especially for
large files. This promotes healthy user psychology.
closes #98
> Update progress bar more frequently.

- getm/reader.py
- tests/test_reader.py
If there's not enough shared memory to accomadate requested chunk
size, reduce chunk size and warn user.
> Reduce chunk_size and warn if /dev/shm constrained
